id: IFBD7C80A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T20:28:48+00:00'
last_modified: '2022-06-08T07:55:50.683283+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24915
  title: འཛམ་གླིང་བྱིས་སྒྲུང་གྲགས་ཅན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    28C3:
      image_group_id: I1KG24917
      title: ''
      total_pages: 358
      order: 1
      base_file: 28C3.txt
    '6137':
      image_group_id: I1KG24918
      title: ''
      total_pages: 358
      order: 2
      base_file: 6137.txt
    7D99:
      image_group_id: I1KG24919
      title: ''
      total_pages: 380
      order: 3
      base_file: 7D99.txt
    B324:
      image_group_id: I1KG24920
      title: ''
      total_pages: 390
      order: 4
      base_file: B324.txt
    58D3:
      image_group_id: I1KG24921
      title: ''
      total_pages: 374
      order: 5
      base_file: 58D3.txt
    49D8:
      image_group_id: I1KG24922
      title: ''
      total_pages: 374
      order: 6
      base_file: 49D8.txt
    0A0A:
      image_group_id: I1KG24923
      title: ''
      total_pages: 340
      order: 7
      base_file: 0A0A.txt
    '4944':
      image_group_id: I1KG24924
      title: ''
      total_pages: 372
      order: 8
      base_file: 4944.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
